In [2]:
# Load the "autoreload" extension so that code can change
%load_ext autoreload

# Always reload modules so that as you change code in src, it gets loaded
%autoreload 2

In [3]:
import tensorflow as tf
from src.models import predict_model, seq2seq
import socialml
import src.data.msg_pipeline as mp
from sklearn.pipeline import Pipeline
import os
import numpy as np
from src.data.word_utils import Vocab

In [4]:
experiment = 'exp02'

In [5]:
checkpoint_dir = os.path.join('../models/checkpoints', experiment)
vocab_filepath = os.path.join(checkpoint_dir, 'vocab.json')
data_spec_filepath = os.path.join('../specs', 'data_specs.yaml')
model_spec_filepath = os.path.join('../specs', experiment+'.yaml')

In [6]:
specs = predict_model.load_yaml(model_spec_filepath)
vocab = Vocab(vocab_filepath)

model, encoder_model, decoder_model = seq2seq.build_model(**specs['model_params'], vocab_size=len(vocab))
original_weights = decoder_model.layers[4].get_weights()
model.load_weights(predict_model.latest_checkpoint(checkpoint_dir))

### Predicting single response

In [260]:
seq_inf = predict_model.SeqInference(vocab_filepath,
                                     encoder_model,
                                     decoder_model,
                                     data_spec_filepath,
                                     verbose=1,
                                     method='beam_search',
                                     max_decoder_seq_length=12)

In [261]:
seq_inf.tokenizer.inverse_transform(4194)

'hello'

In [265]:
msg_ = input('Type a message');
print('\n', 'Sent message: \n', msg_, '\n')
out = seq_inf.predict_response_from_text(msg_)
print('\n', 'Returned message: \n',out)

Type a message hello



 Sent message: 
 hello 

Tokenizing mesage: hello
Sending context: [   2 4194    1] to encoder
Current beam sequence 
 [[    1     2]
 [    1 18624]
 [    1    17]]
Appending [1 2] to final tokens
Current beam sequence 
 [[    1 18624  4767]
 [    1 18624    39]
 [    1 18624     2]]
Appending [    1 18624     2] to final tokens
Current beam sequence 
 [[    1 18624    39     2]
 [    1 18624    39    88]
 [    1 18624    39     7]]
Appending [    1 18624    39     2] to final tokens
Current beam sequence 
 [[    1 18624    39    88     2]
 [    1 18624    39    88    37]
 [    1 18624    39    88   280]]
Appending [    1 18624    39    88     2] to final tokens
Current beam sequence 
 [[    1 18624    39    88    37   280]
 [    1 18624    39    88    37    31]
 [    1 18624    39    88    37     2]]
Appending [    1 18624    39    88    37     2] to final tokens

 Returned message: 
 noooooooo is


### Multiple Resposne

In [290]:
chat = predict_model.Chat(vocab_filepath,
                                     encoder_model,
                                     decoder_model,
                                     data_spec_filepath,
                                     verbose=1,
                                     method='beam_search',
                                     max_decoder_seq_length=12)

In [283]:
chat.reverse_context

True

In [284]:
chat.add_tokens_to_context([1,2,3,4])

In [285]:
import numpy as np

In [286]:
a = np.asarray([1,2,3,4])

In [287]:
a = a[::-1]

In [288]:
a

array([4, 3, 2, 1])

In [292]:
chat.context

[array([    2,    39, 18624,     1]), array([   2, 4194,    1])]

In [301]:
chat.send('hello mate')

Sending context: [   2   16 4194    1] to encoder
Current beam sequence 
 [[ 1  2]
 [ 1 17]
 [ 1  6]]
Appending [1 2] to final tokens
Current beam sequence 
 [[  1   6 174]
 [  1  17 174]
 [  1  17 307]]
Current beam sequence 
 [[  1  17 174 419]
 [  1  17 307   7]
 [  1  17 307  17]]
Current beam sequence 
 [[  1  17 307   7   8]
 [  1  17 307  17   2]
 [  1  17 307  17 419]]
Appending [  1  17 307  17   2] to final tokens
Current beam sequence 
 [[  1  17 307  17 419   8]
 [  1  17 307  17 419 485]
 [  1  17 307  17 419  44]]
Current beam sequence 
 [[  1  17 307  17 419  44  53]
 [  1  17 307  17 419  44  37]
 [  1  17 307  17 419  44 914]]
Current beam sequence 
 [[  1  17 307  17 419  44 914   2]
 [  1  17 307  17 419  44 914 123]
 [  1  17 307  17 419  44 914 229]]
Appending [  1  17 307  17 419  44 914   2] to final tokens
Current beam sequence 
 [[  1  17 307  17 419  44 914 229   2]
 [  1  17 307  17 419  44 914 229  71]
 [  1  17 307  17 419  44 914 229  14]]
Appending [  1  

'i was i'