In [1]:
# Load the "autoreload" extension so that code can change
%load_ext autoreload

# Always reload modules so that as you change code in src, it gets loaded
%autoreload 2

In [2]:
import tensorflow as tf

In [3]:
from src.data.msg_pipeline import Word2Vec, WhiteSpaceTokenizer, Padder
from src.models.tf_dataset_loader import load_from_txt
from sklearn.pipeline import Pipeline
from gensim.models import KeyedVectors
from src.data.word_utils import Vocab
import gensim.downloader as api

In [ ]:
vocab = Vocab('../../data/processed/vocab_pp.json')

In [57]:
word2vec = Word2Vec()

In [62]:
word2vec.special_vectors['<sos>'] = 1

In [58]:
word2vec.set_model(KeyedVectors.load_word2vec_format('../../data/processed/short-vectors.bin.gz'))

In [72]:
word2vec['<sos>']

get item


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

### Scratch

In [ ]:
word2vec['what']

##

In [ ]:
with open('../../data/processed/train/strings_X.txt', 'r') as f:
    X = f.readlines()
with open('../../data/processed/train/strings_Y.txt', 'r') as f:
    Y = f.readlines()
X = [x.strip('\n') for x in X]
Y = [y.strip('\n') for y in Y]
ws = WhiteSpaceTokenizer()
padder = Padder('<pad>')
pipe = Pipeline(steps=[('ws', ws),('pad', padder)])
X_processed = pipe.transform(X)

In [ ]:
def data_generator():
    with open('../../data/processed/train/strings_X.txt', 'r') as f:
        X = f.readlines()
    with open('../../data/processed/train/strings_Y.txt', 'r') as f:
        Y = f.readlines()
    X = [x.strip('\n') for x in X]
    Y = [y.strip('\n') for y in Y]
    ws = WhiteSpaceTokenizer()
    padder = Padder('<pad>')
    pipe = Pipeline(steps=[('ws', ws),('pad', padder)])
    X_processed = pipe.transform(X)
    
    word2vec = Word2Vec()
    model = KeyedVectors.load_word2vec_format('../../data/processed/short-vectors.bin.gz', binary=True)
    word2vec.set_model(model)
    
    for i, x in enumerate(X_processed):
        yield (word2vec.map(x), Y[i])

In [ ]:
class training_data_generator():
    def __init__(self, data_dir, input_fpath, output_fpath):
        self.data_dir = data_dir
        self.input_fpath = input_fpath
        self.output_fpath = output_fpath
#         self.vocab = Vocab()
        self.load_txt()
        self.i = 0
        
    def load_txt(self):
        with open('../../data/processed/train/strings_X.txt') as f:
            X = f.readlines()
        with open('../../data/processed/train/strings_Y.txt') as f:
            Y = f.readlines()
    
    def __iter__(self):
        return self
    
    def __next__(self):
        return self.next()
    
    def next(self):
        self.i+=1
        return X[self.i]
    
    def get(self):
        for i, x in enumerate(X):
            yield x

### Test `load_from_txt`

In [96]:
dataset = load_from_txt('../../data/processed/train/strings_X.txt',
                        '../../data/processed/train/strings_Y.txt',
                        '../../data/processed/short-vectors.bin',
                        '../../data/processed/vocab_pp.json')

Loaded word2vec mapping
Created tf.data.Dataset


In [97]:
it = iter(dataset)

In [98]:
i = next(it)
i

Loaded data from txt file
Removed new line characters
ws tokenized and padded


((<tf.Tensor: shape=(128, 128, 300), dtype=float32, numpy=
  array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
            0.        ,  0.        ],
          [ 0.        ,  0.        ,  0.        , ...,  0.        ,
            0.        ,  0.        ],
          [ 0.        ,  0.        ,  0.        , ...,  0.        ,
            0.        ,  0.        ],
          ...,
          [ 0.        ,  0.        ,  0.        , ...,  0.        ,
            0.        ,  0.        ],
          [ 0.04052734,  0.0625    , -0.01745605, ..., -0.15625   ,
            0.00193024, -0.06982422],
          [ 0.08154297, -0.06396484,  0.02526855, ..., -0.14160156,
           -0.05395508, -0.07666016]],
  
         [[ 0.        ,  0.        ,  0.        , ...,  0.        ,
            0.        ,  0.        ],
          [ 0.        ,  0.        ,  0.        , ...,  0.        ,
            0.        ,  0.        ],
          [ 0.        ,  0.        ,  0.        , ...,  0.        ,
      

In [103]:
i[0]

(<tf.Tensor: shape=(128, 128, 300), dtype=float32, numpy=
 array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         ...,
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [ 0.04052734,  0.0625    , -0.01745605, ..., -0.15625   ,
           0.00193024, -0.06982422],
         [ 0.08154297, -0.06396484,  0.02526855, ..., -0.14160156,
          -0.05395508, -0.07666016]],
 
        [[ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.